Move docs
getoutreach/extensibility-sdk pull request #90
Opened 2023-07-17 18:06 UTC by honeydripper

Moved docs out to Developer Portal

2023-07-17 18:14 UTC, sheff146 requested changes

2023-07-17 18:14 UTC, sheff146 commented on docs/schema/2.0/manifest.schema.json
> -  "$schema": "http://json-schema.org/draft-07/schema#",
Wow, wow! Keep the schema please. It's being used in some places.

2023-07-19 07:44 UTC, sheff146 approved these changes

2023-07-19 08:05 UTC, vSleichert approved these changes

2023-07-19 08:08 UTC, merged